### ISSUE TITLE
Command Does Not Copy EXPIREs

### ISSUE THREAD

**Issue by silvamerica** [reverbdotcom/migr8#1]
For some reason when I tried using this it didn't copy over the TTLs. I'm not exactly sure why.

**Comment by ebenoist** [comment]
@silvamerica I'm not sure either, we have pretty explicit code and coverage around this feature.

https://github.com/reverbdotcom/migr8/blob/master/src/migr8/migrate.go#L35-L50

If you can put together an example, we'd love to take a look.

**Comment by silvamerica** [comment]
It doesn't look like there is a test specifically for the TTL, however. I'll do a test right now.

**Comment by ebenoist** [comment]
Yup, I noticed we're missing test coverage there as well. Feel free to add a test!

**Comment by silvamerica** [comment]
```
[XXX]> PTTL stats_total_201512292210
(integer) 113403
[XXX]> PTTL stats_total_201512292216
(integer) 464209
[XXX]> PTTL stats_total_201512292257
(integer) 2918695

2015/12/29 23:13:22 Running migrate with config: {Dest: [YYY] Source:[XXX] Workers:100 Batch:10 Prefix:stats_total_20151229 ClearDest:false DryRun:true}
migrate - 2015/12/29 23:13:22 Starting Scan with keys stats_total_20151229*
migrate - 2015/12/29 23:13:22 Would have restored stats_total_201512292210 with ttl 0
migrate - 2015/12/29 23:13:22 Would have restored stats_total_201512292216 with ttl 0
migrate - 2015/12/29 23:13:22 Would have restored stats_total_201512292257 with ttl 0
...
```

```
```

**Comment by ebenoist** [comment]
That certainly looks off, can you supply the redis version you're using?

**Comment by silvamerica** [comment]
I just created a [pull request](https://github.com/reverbdotcom/migr8/pull/2) with a test. I'm using Redis 2.8.19.

**Comment by silvamerica** [comment]
Thanks!

**Comment by ebenoist** [comment]
@silvamerica thank you! And please let us know if you see any other issues.
